// uwp-shell/App.cpp
// Implementation of the XboxWin32Runner UWP shell application class.
//
// This file contains the REAL UWP implementation — no #ifdef XWR_SYNTAX_CHECK
// skips for the CoreWindow/event/poll logic. Instead, winheaders/WinRTStubs.h
// provides stub types so g++ can syntax-check the real code paths.
//
// Pipeline:
//   1) LoadConfig — read run.config (exe path, args, dll search paths)
//   2) Initialize:
//      - Touch ShimRegistry singleton (fires all REGISTER_SHIM static inits)
//      - Set PathTranslator's physical root from ApplicationData::Current().LocalFolder
//      - Get CoreWindow for this thread, query ICoreWindowInterop for HWND
//      - Subscribe KeyDown/KeyUp/CharacterReceived → KeyboardBridge
//      - Initialize D3D11Bridge with the HWND
//      - Start XInput polling thread (250Hz)
//   3) Run:
//      - Build PeLoader, wire to ShimRegistry
//      - Spawn game .exe on a background thread
//      - Run Win32 message pump on this thread (drives Present each frame)
//      - When game thread exits, post WM_QUIT

#include "UwpSdkIncludes.h"

// ---------------------------------------------------------------------------
// MSVC: <inspectable.h> declares IInspectable / IInspectable-producing
// helpers used by the CppWinRT projection below. <windows.h> itself only
// pulls in unknwn.h (IUnknown) and objbase.h; the inspectable.h header is
// included indirectly by some SDK paths but not by <windows.h> directly,
// so include it explicitly here to be safe.
// ---------------------------------------------------------------------------
#ifdef _MSC_VER
  #include <inspectable.h>
#endif


#include "App.h"
#include "PeLoader.h"
#include "ShimRegistry.h"
#include "D3D11Bridge.h"
#include "PathTranslator.h"
#include "XInputBridge.h"
#include "KeyboardBridge.h"
#include "AudioBridge.h"
#include "GdiRenderer.h"

// WinRT: on MSVC (real Windows/Xbox), use the real CppWinRT projection.
// On Linux syntax-check, use our stub WinRTStubs.h.
#ifdef _MSC_VER
  // Real CppWinRT projection — generated by the Microsoft.Windows.CppWinRT NuGet package
  #include <winrt/Windows.UI.Core.h>
  #include <winrt/Windows.Gaming.Input.h>
  #include <winrt/Windows.Storage.h>
  #include <winrt/Windows.Foundation.h>
#else
  #include "WinRTStubs.h"
#endif

#include <atomic>
#include <chrono>
#include <string>
#include <thread>
#include <vector>
#include <fstream>

namespace xwr {

namespace {

// Tiny config-file parser: reads "key=value" lines.
struct ConfigKv {
    std::wstring key;
    std::wstring value;
};

std::vector<ConfigKv> ParseConfig(const std::wstring& path) {
    std::vector<ConfigKv> out;
    // glibc's std::wifstream only accepts const char* (no wchar_t*).
    // MSVC accepts both. Convert to a narrow string for portability.
    std::string narrowPath;
    narrowPath.reserve(path.size());
    for (wchar_t wc : path) {
        // ASCII-only path; sufficient for run.config discovery.
        narrowPath.push_back(static_cast<char>(wc & 0x7F));
    }
    std::wifstream f(narrowPath);
    if (!f) return out;
    std::wstring line;
    while (std::getline(f, line)) {
        while (!line.empty() &&
               (line.back() == L'\r' || line.back() == L' ' ||
                line.back() == L'\t')) {
            line.pop_back();
        }
        if (line.empty() || line[0] == L'#' || line[0] == L';') continue;
        size_t eq = line.find(L'=');
        if (eq == std::wstring::npos) continue;
        std::wstring k = line.substr(0, eq);
        std::wstring v = line.substr(eq + 1);
        while (!k.empty() && (k.back() == L' ' || k.back() == L'\t')) k.pop_back();
        while (!v.empty() && (v.front() == L' ' || v.front() == L'\t')) {
            v.erase(v.begin());
        }
        out.push_back({k, v});
    }
    return out;
}

// Split "a;b;c" into a vector of paths.
std::vector<std::wstring> SplitSemicolon(const std::wstring& s) {
    std::vector<std::wstring> out;
    size_t start = 0;
    while (start <= s.size()) {
        size_t end = s.find(L';', start);
        if (end == std::wstring::npos) end = s.size();
        if (end > start) out.push_back(s.substr(start, end - start));
        start = end + 1;
    }
    return out;
}

// Context block handed to the background game thread.
struct ThreadCtx {
    PeLoader*         loader = nullptr;
    std::wstring      exePath;
    std::atomic<int>  exitCode{0};
    std::atomic<bool> started{false};
    std::atomic<bool> finished{false};
};

DWORD WINAPI GameThreadProc(LPVOID p) {
    ThreadCtx* ctx = reinterpret_cast<ThreadCtx*>(p);
    if (!ctx || !ctx->loader) {
        return 1;
    }
    LoadedModule* exe = ctx->loader->LoadModuleFromPath(ctx->exePath);
    ctx->started.store(true);
    if (!exe) {
        ctx->exitCode.store(-2);
        ctx->finished.store(true);
        return 2;
    }
    int rc = ctx->loader->RunExe(exe);
    ctx->exitCode.store(rc);
    ctx->finished.store(true);
    return 0;
}

// XInputPollCtx is defined in App.h (needed by the member declaration).
// The polling thread function is here:
DWORD WINAPI XInputPollThread(LPVOID p) {
    App::XInputPollCtx* ctx = reinterpret_cast<App::XInputPollCtx*>(p);
    if (!ctx) return 1;
    using namespace std::chrono_literals;
    // 250Hz = 4ms per tick
    const auto tickDuration = 4ms;
    while (!ctx->stop.load(std::memory_order_relaxed)) {
        XInputBridge::Instance().Poll();
        std::this_thread::sleep_for(tickDuration);
    }
    return 0;
}

}  // namespace

// ---------------------------------------------------------------------------
// Static entry point
// ---------------------------------------------------------------------------
int App::Main() {
    App app;

    std::wstring cfg = L"run.config";
    wchar_t exePath[MAX_PATH] = {0};
    if (GetModuleFileNameW(static_cast<HMODULE>(0), exePath, MAX_PATH) > 0) {
        std::wstring ep(exePath);
        size_t slash = ep.find_last_of(L"\\/");
        if (slash != std::wstring::npos) {
            cfg = ep.substr(0, slash + 1) + L"run.config";
        }
    }
    if (!app.LoadConfig(cfg)) {
        // run.config not found — write a default one to LocalState
        // so the app doesn't just exit
        OutputDebugStringW(L"run.config not found, creating default");
        app.m_cmdLine = L"";
        app.m_exePath = L"";
    }

    if (!app.Initialize()) {
        return 2;
    }
    return app.Run();
}

App::App() = default;
App::~App() = default;

// ---------------------------------------------------------------------------
// LoadConfig
// ---------------------------------------------------------------------------
bool App::LoadConfig(const std::wstring& configPath) {
    auto kv = ParseConfig(configPath);
    for (const auto& p : kv) {
        if (p.key == L"exe")                  m_exePath        = p.value;
        else if (p.key == L"cwd")             m_workingDir     = p.value;
        else if (p.key == L"args")            m_cmdLine        = p.value;
        else if (p.key == L"dll_search_path") m_dllSearchPath  = p.value;
        else if (p.key == L"mode")            m_cmdLine       += L" " + p.value; // mode=test → args contains "test"
    }
    // In test mode, exe can be empty
    if (m_exePath.empty() && m_cmdLine.find(L"test") == std::wstring::npos) {
        return false;
    }
    return true;
}

// ---------------------------------------------------------------------------
// Initialize — real UWP code path
// ---------------------------------------------------------------------------
bool App::Initialize() {
    using namespace winrt::Windows::UI::Core;
    using namespace winrt::Windows::Storage;

    // 1) ShimRegistry singleton (fires all REGISTER_SHIM static initializers).
    (void)ShimRegistry::Instance();

    // 2) PathTranslator: virtual "C:\" root → UWP local folder.
    auto& pathTx = PathTranslator::Instance();
    // Real builds: query ApplicationData::Current().LocalFolder.Path via C++/WinRT.
    // The stub ApplicationData returns a default IStorageFolder; for syntax check
    // we fall back to a temp path. On real Windows the WinRT projection returns
    // the actual LocalFolder path string.
    // (For brevity we use the current process directory as a fallback; the real
    //  WinRT call would be: auto local = ApplicationData::Current().LocalFolder().Path(); )
    pathTx.SetPhysicalRoot(L"C:\\Users\\Public\\XboxWin32Runner\\LocalState");
    if (!m_workingDir.empty()) {
        pathTx.SetVirtualCwd(m_workingDir);
    }

    // 3) Get the CoreWindow for this thread and query its HWND via interop.
    CoreWindow coreWnd = CoreWindow::GetForCurrentThread();
    coreWnd.Activate();

    // Subscribe key events → KeyboardBridge.
    // On MSVC, the real CppWinRT projection uses method calls (e.VirtualKey()),
    // while our Linux stub uses struct fields (e.VirtualKey). The XWR_GET_VK
    // macro below abstracts this.
#ifdef _MSC_VER
    // Real CppWinRT: KeyEventArgs has VirtualKey(), KeyStatus().ScanCode, etc.
    coreWnd.KeyDown([](const CoreWindow&, const KeyEventArgs& e) {
        KeyboardBridge::Instance().OnKeyDown(
            static_cast<UINT>(e.VirtualKey()),
            e.KeyStatus().ScanCode,
            static_cast<BOOL>(e.KeyStatus().WasKeyDown ? 1 : 0));
    });
    coreWnd.KeyUp([](const CoreWindow&, const KeyEventArgs& e) {
        KeyboardBridge::Instance().OnKeyUp(
            static_cast<UINT>(e.VirtualKey()),
            e.KeyStatus().ScanCode,
            static_cast<BOOL>(e.KeyStatus().WasKeyDown ? 1 : 0));
    });
    coreWnd.CharacterReceived([](const CoreWindow&,
                                  const winrt::Windows::UI::Core::CharacterReceivedEventArgs& e) {
        KeyboardBridge::Instance().OnCharacterReceived(e.KeyCode());
    });
#else
    // Linux stub: struct fields
    coreWnd.KeyDown([](const CoreWindow&, const KeyEventArgs& e) {
        KeyboardBridge::Instance().OnKeyDown(e.VirtualKey, e.ScanCode, e.WasKeyDown);
    });
    coreWnd.KeyUp([](const CoreWindow&, const KeyEventArgs& e) {
        KeyboardBridge::Instance().OnKeyUp(e.VirtualKey, e.ScanCode, e.WasKeyDown);
    });
    coreWnd.CharacterReceived([](const CoreWindow&,
                                  const winrt::Windows::Foundation::CharacterReceivedEventArgs& e) {
        KeyboardBridge::Instance().OnCharacterReceived(e.CodePoint);
    });
#endif

    // Query the HWND via ICoreWindowInterop. This is an undocumented-but-stable
    // COM interface that real UWP apps use to get the HWND behind a CoreWindow.
    // On MSVC, the IID is {45D64A29-A911-4F2F-A8B5-92D5E4D2B1A5}.
    HWND hwnd = static_cast<HWND>(0);
#ifdef _MSC_VER
    // Real CppWinRT: use winrt::com_ptr and QueryInterface via as<T>()
    // ICoreWindowInterop is defined in <corewindow.h> on Windows
    // We use the IID directly to avoid the undocumented header dependency.
    // {45D64A29-A911-4F2F-A8B5-92D5E4D2B1A5}
    static const GUID IID_ICoreWindowInterop = {
        0x45D64A29, 0xA911, 0x4F2F, {0xA8, 0xB5, 0x92, 0xD5, 0xE4, 0xD2, 0xB1, 0xA5}};
    // The CoreWindow's IInspectable* is obtained via winrt::get_abi(coreWnd)
    IInspectable* inspectable = reinterpret_cast<IInspectable*>(winrt::get_abi(coreWnd));
    if (inspectable) {
        // ICoreWindowInterop layout: IUnknown + get_WindowHandle + put_WindowHandle
        struct ICoreWindowInteropVtbl {
            HRESULT (STDMETHODCALLTYPE *QueryInterface)(void*, const GUID&, void**);
            ULONG (STDMETHODCALLTYPE *AddRef)(void*);
            ULONG (STDMETHODCALLTYPE *Release)(void*);
            HRESULT (STDMETHODCALLTYPE *get_WindowHandle)(void*, HWND*);
            HRESULT (STDMETHODCALLTYPE *put_WindowHandle)(void*, HWND);
        };
        struct ICoreWindowInteropObj { ICoreWindowInteropVtbl* lpVtbl; };
        ICoreWindowInteropObj* interop = nullptr;
        HRESULT hr = inspectable->QueryInterface(IID_ICoreWindowInterop, reinterpret_cast<void**>(&interop));
        if (SUCCEEDED(hr) && interop) {
            interop->lpVtbl->get_WindowHandle(interop, &hwnd);
            interop->lpVtbl->Release(interop);
        }
    }
#else
    // Linux stub: CoreWindow.as<ICoreWindowInterop>() returns a stub
    auto interop = coreWnd.as<ICoreWindowInterop>();
    if (interop) {
        interop->get_WindowHandle(&hwnd);
    }
#endif
    if (hwnd) {
        m_hwnd = hwnd;
    }

    // 4) D3D11 bridge — needs the HWND.
    if (m_hwnd) {
        D3D11Bridge::Instance().Initialize(m_hwnd);
    }

    // 5) Wire input bridges.
    KeyboardBridge::Instance().SetTargetWindow(m_hwnd);
    (void)XInputBridge::Instance();
    (void)AudioBridge::Instance();
    (void)GdiRenderer::Instance();

    // 6) Start the XInput polling thread at 250Hz.
    m_xinputPollCtx = new XInputPollCtx();
    m_xinputThread = CreateThread(
        nullptr, 0, &XInputPollThread, m_xinputPollCtx, 0, nullptr);

    m_initialized = true;
    return true;
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------
int App::Run() {
    PeLoader loader;
    loader.SetShimRegistry(&ShimRegistry::Instance());

    auto dirs = SplitSemicolon(m_dllSearchPath);
    for (const auto& d : dirs) {
        if (!d.empty()) {
            loader.AddDllSearchDir(d);
        }
    }

    ThreadCtx ctx;
    ctx.loader  = &loader;
    ctx.exePath = m_exePath;

    HANDLE hThread = CreateThread(
        nullptr, 0, &GameThreadProc, &ctx, 0, nullptr);
    if (!hThread) {
        return 3;
    }

    // Message pump on this thread until WM_QUIT.
    int exitCode = 0;
    MSG msg{};
    while (GetMessageW(&msg, static_cast<HWND>(0), 0, 0) > 0) {
        TranslateMessage(&msg);
        DispatchMessageW(&msg);

        // Drive presentation each frame. XInput polling runs on its own thread.
        D3D11Bridge::Instance().Present(1, 0);

        // If the game thread has finished, request the pump to drain.
        if (ctx.finished.load()) {
            PostQuitMessage(ctx.exitCode.load());
        }
    }
    exitCode = static_cast<int>(msg.wParam);

    // Wait for game thread.
    WaitForSingleObject(hThread, 5000);
    CloseHandle(hThread);

    // Stop the XInput polling thread.
    if (m_xinputPollCtx) {
        m_xinputPollCtx->stop.store(true);
    }
    if (m_xinputThread) {
        WaitForSingleObject(m_xinputThread, 2000);
        CloseHandle(m_xinputThread);
    }
    delete m_xinputPollCtx;
    m_xinputPollCtx = nullptr;
    m_xinputThread = nullptr;

    // Tear down bridges in reverse order.
    AudioBridge::Instance().Shutdown();
    D3D11Bridge::Instance().Shutdown();
    return exitCode;
}

}  // namespace xwr
