using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Windows.Storage;

namespace onitor.Classes
{
    class BlockedDomains
    {
        public static List<string> URL_LIST;

        /// <summary>
        /// True while a YouTube page is the top-level document of a tab.
        /// The YouTube TV player requires Google's IMA ad SDK hosts or
        /// playback stalls on the fallback engine; those hosts stay blocked
        /// everywhere else.
        /// </summary>
        public static bool IsYouTubeContext;

        // Hosts the YouTube TV player needs that domains.txt blocks
        // (imasdk.googleapis.com = Google IMA ad SDK).
        private static readonly System.Collections.Generic.HashSet<string> PlayerRequiredHosts =
            new System.Collections.Generic.HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "imasdk.googleapis.com"
            };

        public static bool IsUrlAllowed(Uri url)
        {
            if (url == null || url.Host == null)
            {
                return true;
            }

            if (IsYouTubeContext && PlayerRequiredHosts.Contains(url.Host))
            {
                return true;
            }

            if (URL_LIST == null)
            {
                URL_LIST = new List<string>();
                ReadDomainList();
            }
            string URL = url.ToString().ToLower();

            if (URL_LIST.Count != 0)
            {

                foreach (string item in URL_LIST)
                {
                    var i = item.ToLower();
                    if (URL.Contains(i))
                    {
                        return false;
                    }
                }
                return true;
            }

            return true;

        }

        public static async void ReadDomainList()
        {
            string fname = @"Assets\domains.txt";
            StorageFolder InstallationFolder = Windows.ApplicationModel.Package.Current.InstalledLocation;
            StorageFile file = await InstallationFolder.GetFileAsync(fname);

            if (File.Exists(file.Path))
            {
                string[] list = File.ReadAllLines(file.Path);
                foreach (var line in list)
                {
                    URL_LIST.Add(line);
                }
            }

        }






        // Thanks to Bashar Astifan for this list and code

        public static string XHRBlocking()
        {
            var xhrHandler = @"var lockdown = false; var blacklist = " + JsonConvert.SerializeObject(URL_LIST) + @"; var xhrbody=false; const origSend = window.XMLHttpRequest.prototype.send; const origOpen = window.XMLHttpRequest.prototype.open; XMLHttpRequest.prototype.open = function (method, url, async, user, password) { this._url = url; var testurl = new URL((this._url.startsWith('http')?this._url:'http://'+this._url)); if(lockdown){console.error('Request blocked due Lock Down mode: '+testurl.hostname); return;} if(blacklist.indexOf(testurl.hostname)!=-1){ console.error('XHR request blocked due blacklist, Target: '+testurl.hostname); console.xhr(`XHR -> blocked to ${this._url}`); return; }  origOpen.apply(this, arguments); };
                                       XMLHttpRequest.prototype.send = function () { var testurl = new URL((this._url.startsWith('http')?this._url:'http://'+this._url)); if(lockdown){console.error('Request blocked due Lock Down mode: '+testurl.hostname); return;} if(blacklist.indexOf(testurl.hostname)!=-1){ console.error('XHR request blocked due blacklist, Target: '+testurl.hostname); console.xhr(`XHR -> blocked to ${this._url}`); return; } if(xhrbody){ console.xhr(`XHR -> ${this._url} body:`, arguments[0]); }else{ console.xhr(`XHR -> sending to ${this._url}`); } origSend.apply(this, arguments); }";


            return xhrHandler;
        }



        public static string ADSProtectionScript()
        {
            var arrayString = JsonConvert.SerializeObject(ADSProtection.ADSProtectionList);
            var adsHandler = @"
                        var adsprotectArray = " + arrayString + @";
                        var AdsProtectionLoaderMonitor = setInterval(function () {   
                        for (var a = 0; a < adsprotectArray.length; a++){
                        try{
                        var selectorBlock = adsprotectArray[a];
                        if(selectorBlock.indexOf('!')==0 || selectorBlock.indexOf('|')==0){
                         return;
                        }
                        if(selectorBlock.indexOf('##')!=-1){
                         var myArr = selectorBlock.split('##');
                         if(myArr.length>1){
                          var HostCheck = myArr[0];
                          selectorBlock = myArr[1];
                          if(!window.location.hostname.includes(HostCheck)){
                            return;
                          }
                          }else{
                          selectorBlock = myArr[0];
                          }
                        }
                        try{
                        var rem = document.querySelectorAll(selectorBlock)
                        try{
                        for (var i = 0; i < rem.length; i++){
                        rem[i].parentNode.removeChild(rem[i]); 
                        if(typeof rem[i].id!='undefined' && rem[i].id.length > 0){
                         console.error('Element '+rem[i].id+' removed due adblock filter');
                        }else if(typeof rem[i].nodeName !='undefined'){
                         console.error('Element ('+rem[i].nodeName+') removed due adblock filter');
                        }else{
                         console.error('Element ? removed due adblock filter');
                        }
                        }
                        }catch(e){
                        }
                        }catch(e){
                        }
                        }catch(e){
                        }
                        }
                        },1500);
                        ";

            return adsHandler;
        }

        public static class ADSProtection
        {
            public static List<string> ADSProtectionList = new List<string>()
        {
            "[id *=google_ads_iframe]",
            "ld-326-6498",
            "#ld-326-6498",
"ld_cli-0",
"#ld_cli-0",
"div[data-outbrain-url]",
".ezAdsense",
".outbrain_widget_0",
".trc_elastic",
".trc_rbox_container",
".trc_related_container",
".trc_spotlight_widget",
".vendor-outbrain",
".yap-loaded",
"[src *='ads_banner']",
"[href^='http://cleanfiles.net/']",
"[href^='https://cleanfiles.net/']",
"[href^='http://cf-getfile.com/']",
"[href^='https://cf-getfile.com/']",
"[href^='http://clnks.co/']",
"[href^='http://downloadity.net/']",
"[href^='http://dream-file.com/']",
"[href^='http://fileice.net/']",
"[href^='http://fileunlckr.com/']",
"[href^='http://linkz.it/']",
"[href^='https://www.cpagrip.com/']",
"[href^='http://adscendmedia.com/']",
"[href^='http://adworkmedia.com/']",
"[href^='http://ulock.it/']",
"[href^='http://www.hacksandcodes.com/']",
"[href^='http://www.hdplugindownload.com/']",
"[href^='http://tinyfileshost.com/']",
"[href^='http://filespeedy.net/']",
"[href^='http://hostujmy.pl/']",
"[href^='http://topfiles.me/']",
"[href^='http://filenix.com/']",
"[href^='http://jlyse.net/']",
"[href^='https://jlyse.net/']",
"[href^='http://getfiles.co/']",
"[href^='http://gripped.biz/']",
"[href^='http://dollarupload.com/']",
"[href^='http://offershare.org/']",
"[href^='http://sharebay.net/']",
"[href^='http://seashare.net/']",
"[href^='http://sharkyfiles.com/']",
"[href^='http://burnshare.net/']",
"[href^='http://saveftp.com/']",
"[href^='http://www.firecash.org/']",
"[href^='http://firecash.org/']",
"[href^='http://mwfiles.net/']",
"[href^='http://up-flow.org/']",
"[href^='http://filecom.net/']",
"[href^='http://gigup.pl/']",
"[href^='http://gotlinks.co/']",
"[href^='http://file-speedy.com/']",
"[href^='http://fileblckr.com/']",
"[href^='http://filesmy.com/']",
"[href^='http://getmyfile.org/']",
"[href^='http://flamefile.com/']",
"[href^='http://playwatch.pl/']",
"[href^='http://ubfiles.com/']",
"[href^='http://zippydownloads.com/']",
"[href^='http://redirectlock.com/']",
"[href^='http://evodownload.com/']",
"[href^='http://zoomfiles.net/']",
"[href^='http://shortz.so/']",
"[href^='http://fileam.com/']",
"[href^='http://filerack.net/']",
"[href^='http://megadown.us/']",
"[href^='http://quelldateien.de/']",
"[href^='http://fichierload.fr/']",
"[href^='http://okfiles.net/']",
"[href^='http://filesquick.net/']",
"[href^='http://clixtk.com/']",
"[href^='http://jofiles.com/']",
"[href^='http://yourfreesoftonline.com/']",
"[href^='http://gotgamecheats.net/']",
"[href^='http://fileups.net/']",
"[href^='http://swiftdownload.net/']",
"[href^='http://lockredirect.com/']",
"[href^='http://reliabledownloads.org/']",
"[href^='http://www.needforfile.net/']",
"[href^='http://fileme.us/']",
"[href^='http://gripfile.net/']",
"[href^='http://www.onlyfiles.net/']",
"[href^='http://astucetriche.fr/']",
"[href^='http://onlinegamesfiles.com/']",
"[href^='http://bestgamesfiles.com/']",
"[href^='http://mysoftwareplace.com/']",
"[href^='http://worldsoftwaredownloads.com/']",
"[href^='http://youronlinesoft.com/']",
"[href^='http://digitalsoftwareonlinenow.com/']",
"[href^='http://yourfreegamesnow.com/']",
"[href^='http://yourgamesdownloads.com/']",
"[href^='http://starmediasearch.com/']",
"[href^='http://mediasearchdirect.com/']",
"[href^='http://morenewmedia.com/']",
"[href^='http://promediasearch.com/']",
"[href^='http://upshare.org/']",
"[href^='http://skippyfile.com/']",
"[href^='http://xtremgenerators.com/']",
"[href^='http://www.xtremgenerators.com/']",
"[href^='http://topgamehax.com/']",
"[href^='http://www.topgamehax.com/']",
"[href^='http://verallohacks.com/']",
"[href^='http://filebandit.net/']",
"[href^='http://fileml.com/']",
"[href^='http://sharecash.org/']",
"[href^='http://www.linkz.it/']",
"[href^='http://jafiles.net/']",
"[href^='http://lnkgt.com/']",
"[href^='http://filesrightnow.com/']",
"[href^='http://gripdownload.com/']",
"[href^='http://www.gripdownload.com/']",
"[href^='http://speedyfiles.net/']",
"[href^='https://www.lockredirect.com/']",
"[href^='http://www.mannesoth.com/']",
"[href^='http://www.downloadthesefiles.com/']",
"[href^='http://downloadsfreesoftwares.com/']",
"[href^='http://fileskeep.com/']",
"[href^='http://www.boltfiles.com/']",
"[href^='http://filespeedy.org/']",
"[href^='http://verified-download.com/']",
"[href^='http://www.highcash.org/']",
"[href^='http://booshare.net/']",
"[href^='http://pushcloud.org/']",
"[href^='http://fileurl.me/']",
"[href^='http://qwiklnk.com/']",
"[href^='http://reliablefiles.com/']",
"[href^='http://www.generaldownload.com/']",
"[href^='http://files.cat/']",
"[href^='http://yourdigitalsearcher.com/']",
"[href^='http://smartmediasearcher.com/']",
"[href^='http://gripfiles.com/']",
"[href^='http://fdownload52.com/']",
"[href^='http://downupfiles.com/']",
"[href^='http://track.cmllk1.info/']",
"[href^='http://gripdownloads.co/']",
"[href^='http://www.v4download.com/']",
"[href^='http://grippedownloads.co/']",
"[href^='http://www.tricheurhq.com/']",
"[href^='http://gripnode.co/']",
"[href^='https://gripfiles.net/']",
"[href^='http://yourfreemediadownloads.com/']",
"[href^='http://myfreedownloadsnow.com/']",
"[href^='http://edgydownload.com/']",
"[href^='http://grabfile.co/']",
"[href^='http://seizefile.co/']",
"[href^='http://stream.aff-id.com/']",
"[href^='http://streams.aff-id.com/']",
"[href^='http://tv.aff-id.com/']",
"[href^='http://play.affmob.org/']",
"[href^='http://gripconfirmation.com/']",
"[href^='http://fileston.com/']",
"[href^='http://filedirection.com/']",
"[href^='http://grabclicks.com/']",
"[href^='http://fileconfirmation.com/']",
"[href^='http://gripclix.com/']",
"[href^='http://flamefolders.com/']",
"[href^='http://grptrker.com/']",
"[href^='http://mayukefile.com/']",
"[href^='http://filesyncing.net/']",
"[href^='http://stream.mobig.gr/']",
"[href^='http://epctrking.com/']",
"[href^='https://epctrking.com/']",
"[href^='https://quickdl.net/']",
"[href^='https://www.filetrkr.com/']",
"[href^='https://filetrkr.com/']",
"[href^='http://filetrkr.com/']",
"[href^='http://www.filetrkr.com/']",
"[href^='https://royalfolders.com/']",
"[href^='http://royalfolders.com/']",
"ads2-pos-101-ad-banner",
"ads2-pos-121-ad-right",
"adslot300x250ATF",
"adslot300x250BTF",
"adsmobileBottom",
"betald-widget",
"better-ads-2",
"better-ads-5",
"catfish",
"catfishcookie",
"colombiaAdBox",
"dcmr1__slot",
"dcmr2__slot",
"dcmr3__slot",
"disqus_thread",
"disqus-comments",
"div[id*='block-itg-ads-']",
"div[id*='div-gpt-ad-']",
"div_gpt_mpu",
"div-gpt-ad-mobile_footer",
"div-gpt-ad-mobile_leaderboard",
"dlb1__slot",
"dlb2__slot",
"dlb3__slot",
"dmr1__slot",
"dmr2__slot",
"dmr3__slot",
"fbs-ad-rail-article-0",
"first_ad_bs",
"firstsocial",
"foxpush_overlay",
"headerAds728x90",
"imgads",
"insticator-container",
"listad",
"main-ads",
"masthead-ad",
"mobile-ad-container",
"my-adsLDRB",
"pushSec",
"RTK_3XT7",
"RTK_gtqV",
"stickyad",
"topAd",
"vuukle_div",
"vuukle_env",
"#ads2-pos-101-ad-banner",
"#ads2-pos-121-ad-right",
"#adslot300x250ATF",
"#adslot300x250BTF",
"#adsmobileBottom",
"#betald-widget",
"#better-ads-2",
"#better-ads-5",
"#catfish",
"#catfishcookie",
"#colombiaAdBox",
"#dcmr1__slot",
"#dcmr2__slot",
"#dcmr3__slot",
"#disqus_thread",
"#disqus-comments",
"div[id*='block-itg-ads-']",
"div[id*='div-gpt-ad-']",
"#div_gpt_mpu",
"#div-gpt-ad-mobile_footer",
"#vdiv-gpt-ad-mobile_leaderboard",
"#dlb1__slot",
"#dlb2__slot",
"#dlb3__slot",
"#dmr1__slot",
"#dmr2__slot",
"#dmr3__slot",
"#fbs-ad-rail-article-0",
"#first_ad_bs",
"#firstsocial",
"#foxpush_overlay",
"#headerAds728x90",
"#imgads",
"#insticator-container",
"#listad",
"#main-ads",
"#masthead-ad",
"#mobile-ad-container",
"#my-adsLDRB",
"#pushSec",
"#RTK_3XT7",
"#RTK_gtqV",
"#stickyad",
"#topAd",
"#vuukle_div",
"#vuukle_env",
".__ads",
".__footer_ads",
".__taboola_story_widget",
".abo_link",
".ad",
".ad.wgt",
".ad__athena_internal",
".Ad__Wrapper",
".ad_300x100",
".ad_300x250",
".ad_banner",
".ad_btw",
".ad_container",
".ad_container.section",
".ad_dfp",
".ad_Home_top",
".ad_label_method",
".ad100",
".ad200",
".ad250x300",
".ad300",
".ad-300",
".ad300x375",
".ad728_cont",
".ad-amp-flex-bottom",
".ad-banner",
".ad-banner-container",
".ad-banner-in",
".ad-banner-wrapper",
".adblock",
".ad-block__inner",
".ad-blocker-ajax",
".adblock-unused",
".adbox",
".ad-box",
".adbox-border",
".adbox-border-desk",
".adboxtop",
".ad-bx",
".adcenter",
".ad-cntainer",
".adcont",
".adcontainer",
".ad-container",
".adContentLeft",
".ad-declare",
".ad-display-wrapper",
".ad-header-container",
".adHolderStory",
".ad-label",
".ad-leaderboard",
".adloc-is-banner",
".ad-mark",
".ad-mobile",
".ad-mobile-flex-pos2",
".ad-mobile-flex-top",
".ad-next-arrow",
".ad-non-sticky",
".adprocess",
".ads",
".ads_area_728X90",
".ads_unit",
".ads-advlabel",
".adsbg300",
".adsbox970x90",
".adsbox990x90",
".adsbygoogle",
".adsbypure",
".adsection",
".ad-section",
".ad-section-one",
".ad-section-three",
".ad-section-two",
".adslot",
".ad-slot",
".ads-mobi-block",
".adspace-lb",
".adspace-lr",
".ads-placment",
".adswrapper",
".ad-taboola-a",
".adtester-container",
".adtext",
".ad-text",
".ad-top-banner",
".ad-unit",
".adunitContainer",
".adunit-purch",
".adv",
".adv_300",
".adv_bg",
".adv2",
".advads-sticky",
".advert",
".advertisement",
".advertisement-250",
".advertisement-middle",
".advertisements",
".advertisements-link",
".advertisemnet_in_header",
".advertise-with-us-in-ad-wrap",
".advertising",
".adv-generic-container",
".advoice",
".ad-withborder",
".ad-wrapper",
".amazon-ad",
".amazon-widget",
".amp_ab_consumption_share",
".amp_Ad",
".amp_Ad_4",
".amp-ad-container",
".ampads",
".app_teaser",
".app-download-interstitial--open",
".append_social_share",
".app-ico",
".appIcon",
".AppPromo",
".appPromotion",
".appstext",
".app-top-ad",
".aroundthewebconatiner",
".article__comment",
".article__details__share",
".article__feedbacklink",
".article__share-buttons",
".article__sharing",
".article__socials",
".article__whatsapp",
".article_fb_comments",
".article_separator",
".article-adver",
".article-body__share-icons",
".article-bottom-newsletter-promo",
".article-function-social-media",
".articleSep",
".article-share",
".article-share-sheet",
".article-shop-bar",
".article-social",
".article-sponsored-content-list",
".a-socialicon",
".asset-social-media",
".as-sharing-close",
".as-sharing-container",
".as-sharing-open",
".as-social",
".atc-ContainerSocialMedia",
".atf_ad300",
".av-share-box",
".aw-campaigns",
".banner_ads_home_inner",
".banner300x600",
".banner-336x280",
".banner-before-featured-post",
".banner-container__right--banner-widgets",
".banner-display-ad-mobile",
".bannergroupbutton",
".banner-grp",
".banner-next-article",
".bannerRelease",
".banner-right",
".banner-section",
".banner-top-wrapper",
".banner-wrapper",
".bar_ebook",
".bd-sponser-cont",
".betald-section",
".block-itg-ads",
".buysellads_sidebar",
".c1.m-hp-ad",
".c-ad__medium-rectangle",
".c-entry-box__meta",
".c-entry-hero__meta",
".channel__ad-header",
".col--ad",
".colombia",
".colombiaAd",
".colombiaAdbox",
".columbia_twins",
".columbiaAds",
".contained-ad-container",
".CONTENT_AD",
".c-social-bar",
".c-social-bar--is-sticky",
".c-taboola",
".cta-btn",
".custom-share",
".disqus",
".disqus_comment_bx",
".disqus-comments",
".disqus-wrap",
".engagement-ad",
".fb_cmtitle",
".fbcomments",
".fbs-ad--ntv-mobhome-wrapper",
".fbs-ad--progressive",
".fbs-ad--top-wrapper--desktop",
".fe-adsbox",
".fixedsocial",
".ggnoads",
".googlead",
".gshre-box",
".gsocialbar",
".gutter-ads",
".has-ad",
".hcf-ad-rectangle",
".hcf-ad-wrapper",
".hcf-sponsoring",
".home-ad-728-90",
".home-social-block",
".id_bottom_ad",
".id_footer_social",
".in-article-adsense",
".internalAd",
".ipad300crowdy",
".js-share-bar",
".js-subscription-combo-box",
".kip-advertisement",
".kip-advertisement-fixed",
".lazyadslot",
".level-1-ad-desktop",
".level-1-ad-mobile",
".level-after-3-ad-desktop",
".m-ad",
".m-advert",
".midad",
".m-mem-ad",
".mob-bottom-fixed-ad",
".mobile_ads",
".mobile_hide",
".mobile_share",
".mobileAd",
".mobile-ad",
".mobile-body-ad",
".mobile-insta-adv",
".mobile-story-ad",
".mobile-ticket-ad__AdWrapper-s1c4io30-0",
".mod-ad",
".movable-ad",
".m-river--ad",
".m-social",
".m-story-ad--full",
".m-story-meta__share-actions",
".m-story-meta__shares",
".mt-30.promotional-feature-ads",
".mv_button_css",
".nativead",
".nc_socialPanel",
".nd-ad",
".NewsArticle__Ad",
".ntv-rail-ad",
".o-listing__ad",
".o-mobile-share-footer",
".postbit-social",
".post-share",
".PostSocial",
".post-socialmedia",
".post-social-mobile",
".PrivacyCookieAccepted",
".profolio-ad",
".promo_heavy_container",
".promo_link",
".promo-banner",
".promo-block",
".promoloaded",
".promoted",
".promotext",
".promotion",
".promotional-content",
".promotional-feature-ads",
".promotion-single-banner",
".promo-wrapper",
".provAd",
".purchad",
".revive-header-ad",
".river-ad",
".rtAdContainer",
".rw_ad",
".s_share_box",
".share-article-button",
".sharebar",
".sharebelow",
".share-box",
".share-btn-wrp",
".share-container",
".sharedaddy",
".shareDiv",
".shareholder",
".share-links-wrapper",
".shareMenu",
".share-social",
".share-this",
".share-this-popover",
".s-home-adv-banner",
".social_share",
".socialbar",
".social-block",
".social-blog",
".socialBox",
".social-container",
".social-list-icon",
".social-media-icons",
".social-shar-bar",
".social-share",
".socialShareBar2",
".socialshare-rightsec",
".social-shares",
".socialShareWrap",
".social-share-wrap",
".social-sharing-bot",
".social-sharing-top",
".socialSpace",
".social-widget2",
".special-anzeige",
".special-promo",
".spnrsBx",
".spon_lwrp",
".sponcer",
".sponsered-by-chart",
".sponserlink",
".sponserLogoHolder",
".sponsor",
".sponsor_panel",
".sponsor-banner",
".sponsorContainer",
".sponsor-dyn-banner",
".sponsored_sec",
".sponsored-headlines",
".sponsors",
".sponsorSlide",
".sponsors-wrap",
".sport-ad2",
".sports_ads",
".square-ad",
".starstruck-wrap",
".sticky_ad_container",
".story__social",
".story_social",
".story_social_share",
".story-page-ad",
".story-page-content-ad",
".story-top-ad",
".superbanner",
".taboola",
".todayshowcasead",
".top_ad",
".top_bigAds",
".top_share_widget",
".top-ad-container",
".topadd",
".topArtAd",
".topbanner",
".topbannerad",
".top-banner-box",
".topic-ads",
".top-promo",
".topsponsors",
".total-share-container",
".trend-ad-wrap",
".trending-add",
".uniq-ads",
".view-ads",
".vuukle",
".vuuklebox",
".vuukle-powerbar",
".wid_tboola",
".widead",
".widget.ad",
".widget.editor-box",
".with_ad",
".wrapad",
".zt_add",
"[href*='//ceptavou.net/']",
"[href*='//chauksoa.net']",
"[href*='//chidsimp.com']",
"[href*='//ousufauk.com/']",
"[href*='//pegloang.com/']",
"[href*='//taiwhups.net/']",
"[href*='//thiksikr.com/']",
"[href*='//wedeegut.net/']",
"[href*='/18-adult/']",
"[href*='/gewinnspiele']",
"[href*='18movies']",
"[href*='1958455.html']",
"[href*='checkabil.com']",
"[href*='checkabil.itm']",
"[href*='gomotube']",
"[href*='http://ads.forbes.com/']",
"[href*='https://bnc.lt/']",
"[href*='https://cybershield.cc']",
"[href*='newstatusvideos.com']",
"[href*='newstatusvideos.itm']",
"[href*='preferredain.com']",
"[href*='preferredain.itm']",
"[href^='../out.php']",
"[href^='./out.php']",
"[href^='http://cntraveller.in/newsletter-signup/']",
"[href^='http://install.thezeebusiness.com/']",
"[href^='https://go.onelink.me/unJQ']",
"[href^='https://greatlearning.in/great-lakes-pgpba']",
"[href^='https://hotdeals360.com/']",
"[href^='https://hvp98.app.goo.gl/']",
"[href^='https://pages.email.fortune.com/newsletters/']",
"[href^='https://pl.allsports4free.club/']",
"[href^='https://playandwingame.india.com/']",
"[href^='https://subscribe.timesgroup.com/']",
"[href^='https://swachhindia.ndtv.com/']",
"[href^='https://transactmoneycontrol.page.link/']",
"[href^='https://videoblocks.go2cloud.org/aff_c']",
"[href^='https://www.amazon.in/b']",
"[href^='https://www.crichd.com/link.php']",
"[href='//o12zs3u2n.com/1523675.html']",
"[href='//ptikeegno.com/1803695.html']",
"[href='//zukxd6fkxqn.com/1573881.html']",
"[href='//zukxd6fkxqn.com/804548.html']",
"[href='/swasthimmunisedindia/']",
"[href='/tata-steel']",
"[href='http://2analsex.com/']",
"[href='http://2analsex.itm/']",
"[href='http://bit.ly/2WIl17I']",
"[href='http://prefiles.com/register-6149.html']",
"[href='http://yomovies.it/genre/18/']",
"[href='http://yomovies.org/genre/18/']",
"[href='https://1337xhd.in/category/18-adult-movies/']",
"[href='https://2movierulz.ac/category/adult-18/']",
"[href='https://99anal.com/']",
"[href='https://99anal.itm/']",
"[href='https://bit.ly/2OuNdmM']",
"[href='https://djmaza.fun/SnakeVsBlocksGame.apk']",
"[href='https://forum.xda-developers.com/getbrave']",
"[href='https://hindilinks4u.co/genre/18/']",
"[href='https://moneycontrol.com/promos/pro.php']",
"[href='https://news18.com/mission-pani/']",
"[href='https://news18.com/whatsapp_broadcast.html']",
"[href='https://oneindia.com/save-life/']",
"[href='https://prmovies.co/genre/18/']",
"[href='https://s.to/gewinnspiel']",
"[href='https://timesofindia.onelink.me/efRt/GetAppMwebHome']",
"[href='https://videoblocks.go2cloud.org/SH2g']",
"[href='https://www.colombiaonline.com/']",
"[href='https://www9.onlinemoviewatch.org/download-onlinemoviewatchs-app']",
"[href='https://yomovies.it/genre/18/']",
"[href='https://yomovies.org/genre/18/']",
"[href='newscomm-33611.php']",
"[src*='/amazon-associate/']",
"[src*='https://mobiletipswork.store/ads/']",
"[src*='whatapps-icon']",
"[src^='https://widget.getyourguide.com']",
"[src='//dianomi.com/recirculation.epl?id=66']",
"[src='/kismet/spacer.png']",
"[src='http://i.imgur.com/k9valni.png']",
"[src='http://movies777.org/wp-content/uploads/88.jpg']",
"[src='https://djmaza.com/ads/download-button.png']",
"[src='https://forum.xda-developers.com/op7prolaunch3.html']",
"[src='https://xda-developers.com/op7_launch.html']",
"a[href*='https://goibibo.com/offers/international-hotels/']",
"a[href^='/watchfree.php']",
"a[href^='magnet:']",
"a[href='/ad-free']",
"a[href='http://forum.xda-developers.com/ad-free']",
"a[href='http://www.crichd.im/footy/']",
"a[href='http://www.crichd.info/footy/']",
"amp-ad",
"dfp-ad",
"div[id*='div-gpt-ad-']",
"div[id*='ezoic-pub-ad-placeholder-']",
"div[id*='gpt-']",
"div[id^='div-gpt-ad-']",
"div[id^='test_ad_']",

        };
        }


    }
}
